services:
  node:
    container_name: node
    image: node:20-alpine
    working_dir: /var/www/html/app/
    user: node
    volumes:
      - ./:/var/www/html/app/
    ports:
      - 1337:1337
    tty: true
    stdin_open: true
    command: sh -c "npm i && npx prisma generate && npm run dev"

  db:
    image: postgres:16
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

volumes:
  db-data:
