version: "3"

services:
  node:
    container_name: node
    image: node:20-alpine
    working_dir: /var/www/html/app/
    user: node
    volumes:
      - ./:/var/www/html/app/
    ports:
      - 8000:8000
    tty: true
    stdin_open: true
    command: sh -c "npm i && npx prisma generate && npm run dev"
    depends_on:
      - db
      - ollama
    environment:
      OLLAMA_URL: http://localhost:11434/

  db:
    image: postgres:16
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"

volumes:
  db-data:
